<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>winExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Emgu.CV" Version="4.11.0.5746" />
    <PackageReference Include="Emgu.CV.Bitmap" Version="4.11.0.5746" />
    <PackageReference Include="Emgu.CV.runtime.windows" Version="4.11.0.5746" />
    <PackageReference Include="LibVLCSharp.WPF" Version="3.9.4" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.23.1" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
    <PackageReference Include="Whisper.net" Version="1.8.1" />
    <PackageReference Include="Whisper.net.Runtime" Version="1.8.1" />
    <PackageReference Include="Whisper.net.Runtime.Cuda.Windows" Version="1.8.1" />
    <PackageReference Include="Whisper.net.Runtime.OpenVino" Version="1.8.1" />
    <PackageReference Include="Whisper.net.Runtime.Vulkan" Version="1.8.1" />
    <PackageReference Include="WPF-UI" Version="4.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ffmpeg\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Remove="ffmpeg\ggml-large-v3-turbo-q5_0.bin" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
